name: CI Action
on:
  pull_request:
    branches:
      - main

jobs:
  ci-dns-proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run
        env:
          DOMAIN: example.com
        uses: ./ # Uses an action in the root directory

      - name: cat output file
        run: cat example-com.jsonl
